Convert all docs/*.html to .md
openssl/web pull request #345
Opened 2022-07-11 15:59 UTC by levitte

We only take the easy parts, and leave manual page generation files alone.

Partial fix of #324

2022-07-11 23:17 UTC, paulidale approved these changes

2022-07-12 06:41 UTC, levitte commented
Actually, I had a thought with this one that will need re-approval later

2022-07-12 06:58 UTC, paulidale requested changes

2022-07-12 06:58 UTC, paulidale commented on docs/fips.md
> +-   The OpenSSL FIPS Object Module 2.0 validation is \"delivered\" in
Spurious \\ here and later

2022-07-12 08:52 UTC, levitte commented on docs/fips.md
> +-   The OpenSSL FIPS Object Module 2.0 validation is \"delivered\" in
Fixed most of them

2022-07-12 08:52 UTC, paulidale approved these changes

2022-07-12 10:21 UTC, levitte commented
There were a few more files to fix...  Re-approval needed

2022-07-13 04:14 UTC, paulidale submitted a review, later dismissed

2022-07-14 07:02 UTC, levitte commented
I noticed this work wasn't quite complete, so back to draft

2022-07-15 04:41 UTC, levitte commented
Rebased and squashed

2022-07-15 09:51 UTC, levitte commented
Squashed and generally cleaned up

2022-07-15 09:52 UTC, levitte commented
https://beta.openssl.org/ is the test bed for this

2022-07-15 10:06 UTC, t8m commented
I see some _interesting_ files in the directory list at: https://beta.openssl.org/docs/fips.html
- the .md files and dirdata.yaml in particular. Can we somehow filter them out?

2022-07-16 06:14 UTC, levitte commented
> I see some _interesting_ files in the directory list at: https://beta.openssl.org/docs/fips.html
> 
>     * the .md files and dirdata.yaml in particular. Can we somehow filter them out?

Yes, see 568c8e4fa30deb06b83cacb2924ec60f19515ff1

2022-07-18 07:25 UTC, t8m reviewed
Now the only glitch I see in docs on beta.openssl.org is that there are manual pages only for the master branch. The rest is giving a weird 404 page. For example: https://beta.openssl.org/docs/man3.0

2022-07-19 07:08 UTC, levitte commented
Ping

2022-07-19 07:32 UTC, t8m commented
@levitte Is my comment above relevant?

2022-07-19 08:11 UTC, levitte commented
> Now the only glitch I see in docs on beta.openssl.org is that there are manual pages only for the master branch. The rest is giving a weird 404 page. For example: https://beta.openssl.org/docs/man3.0

The default `make` command only builds the master docs...  I'm running `make docs` now, which builds the whole set...  so er, in 15-20 minutes?

2022-07-19 08:25 UTC, levitte commented
> > Now the only glitch I see in docs on beta.openssl.org is that there are manual pages only for the master branch. The rest is giving a weird 404 page. For example: https://beta.openssl.org/docs/man3.0
> 
> The default `make` command only builds the master docs... I'm running `make docs` now, which builds the whole set... so er, in 15-20 minutes?

Done

2022-07-19 08:34 UTC, t8m commented
LGTM

2022-07-19 08:43 UTC, levitte commented
> LGTM

@openssl/omc, final review?

2022-07-20 10:38 UTC, mattcaswell approved these changes

2022-07-20 11:09 UTC, levitte commented
Merged

9d6ac3f1db833a495df684429215e31c76c8ea4e Convert docs/*.html to .md
964dd4386ddb005b1dc52eb197ac53f4686041b2 Convert docs/sub-*.html.tt to .md.tt
18aaf09b6e2dc3b4e1194d561059cec9a2339155 bin/from-tt: Correct bugs for determining [% top %]
e0824ffd90afab8425e01c90594c03b13d9d9975 Bugfix: make knows $(dir ...), not $(dirname ...)

2022-07-20 11:09 UTC, closed without merging