Update pink nirvana and related documentation.
openssl/web pull request #380
Opened 2022-11-11 05:12 UTC by slontis

I have seen multiple instances of references to the design document, and in a few cases copying of the pink nirvana diagram - so it was time to update date it to match what we currently have. Also changed text related to the engine provider, since that was completely misleading.

2022-11-11 10:05 UTC, mattcaswell requested changes
It the old design document actually linked anywhere on our website?

2022-11-11 10:05 UTC, mattcaswell commented on docs/OpenSSL300Design.md
> +    when called via the Core. ~~
Maybe repeat the text "This was not implemented"...or just delete it

2022-11-11 10:05 UTC, mattcaswell commented on docs/OpenSSL300Design.md
>      algorithms.
It seems you intended to delete this old version of the text

2022-11-11 10:05 UTC, mattcaswell commented on docs/OpenSSL300Design.md
> +[The ENGINE API](#the-engine-api) further down.~~
Perhaps preface this with "It was originally intended that Engines would have a provider shim..."

2022-11-11 10:05 UTC, mattcaswell commented on docs/OpenSSL300Design.md
> +        based approach.~~ This was not implemented.
Should we just delete this line?

2022-11-15 01:01 UTC, slontis commented
> It the old design document actually linked anywhere on our website?

Not that I can find.. Apart from the sitemap. It is getting found somehow.

2022-11-15 01:12 UTC, slontis commented
Updated - mainly by deleting engine related comments.

2022-11-15 11:33 UTC, mattcaswell requested changes

2022-11-15 11:33 UTC, mattcaswell commented on docs/OpenSSL300Design.md
> +    provider requires this since it does not contains methods to
s/contains/contain/

2022-11-15 11:33 UTC, mattcaswell commented on docs/OpenSSL300Design.md
> +    load keys. The Base provider is also embedded in the core.
"the core" may not be entirely clear. Do you mean "embedded in the default provider"?

2022-11-16 12:00 UTC, mattcaswell approved these changes

2022-11-16 13:23 UTC, romen commented
This looks like a very good initiative to me, and would approve this, but I wanted to ask you first what do you think about the fact that in the 300_components and 300_packaging diagrams the 3rd party ENGINEs completely disappear: I am fine with it being that way in the `ToBe_*`` diagrams, as that is explained in the updated text, but in 3.0 the diagram does not show anymore how external ENGINEs fit in 3.0, where they still have some level of support.

2022-11-16 21:18 UTC, slontis commented
I think it is sufficient to explain it in the document itself. Trying to draw it is probably not going to make it clear.

2023-01-05 10:54 UTC, levitte commented
Merged

cc2c09421b4a3cf42ab8847afdf4baa75ce7e98b Update pink nirvana and related documentation.

2023-01-05 10:54 UTC, closed without merging