Update roadmap
openssl/web pull request #442
Opened 2023-11-24 08:04 UTC by hlandau

Rough draft of a new roadmap document so we at least have something to communicate for now.

We need to decide what to put in the FIPS section. Taking suggestions here.

(If @anton wants to take over this PR, that's fine also)

2023-11-24 08:11 UTC, t8m requested changes

2023-11-24 08:11 UTC, t8m commented on roadmap.md
> +TODO TALK ABOUT FIPS
I would remove the section for now. Or just mention that we are still working on FIPS 140-3 validation of OpenSSL. I would not mention a particular version.

2023-11-24 08:21 UTC, hlandau commented
How's this?

2023-11-24 09:18 UTC, t8m approved these changes

2023-11-28 08:45 UTC, arapov commented
@hlandau, it is good; thanks for capturing it; it is a big help for me.

Please keep this PR open until the end of the week at the latest. I'll see if I want to add something to the text.

2023-12-04 18:20 UTC, DDvO commented
I just wonder why the section "**Post-quantum cryptography**" has been removed.
Doesn't this include helpful clarification and a nice hint to use the Open Quantum Safe provider?

2023-12-21 05:17 UTC, JefriReynaldi approved these changes

2023-12-21 05:17 UTC, JefriReynaldi commented on roadmap.md
>  # OpenSSL project roadmap
```dart

```

2023-12-21 21:18 UTC, kroeckx commented
This doesn't really look like a roadmap. I hope we plan to do more than just quic, maybe performance, and fips.

2023-12-22 12:41 UTC, t8m commented
> This doesn't really look like a roadmap. I hope we plan to do more than just quic, maybe performance, and fips.

It is very brief but for 3.3 we do not have that much time left and for 3.4 we really need the release steering committee to decide. I think this should be merged and then updated soon after 3.4 plans are established.

2023-12-22 12:41 UTC, t8m commented
@arapov please approve

2023-12-22 13:27 UTC, arapov commented
> This doesn't really look like a roadmap. I hope we plan to do more than just quic, maybe performance, and fips.

We don't commit to anything but QUIC, although performance and fips are top priorities that are worked on.

2023-12-22 13:27 UTC, arapov commented
> @arapov please approve

Not yet. I need to update it.

2023-12-22 17:47 UTC, kroeckx commented
Why should this only cover 3.3? There are lots of things we want to do. We don't know when, but we do plan to do it at some point.

2024-01-10 14:35 UTC, ghost commented
@arapov Anton is about to update this issue.

2024-01-10 14:40 UTC, Fitnesskrokodyl commented
Clean up the page. @arapov

2024-01-11 07:24 UTC, arapov commented
closed in favour of #446

2024-01-11 07:24 UTC, closed without merging