update roadmap for 3.4
openssl/web pull request #481
Opened 2024-04-22 13:03 UTC by nhorman

Add in epic items that we have planned for 3.4 and reference the running 3.4 schedule

Fixes #24219

2024-04-22 13:55 UTC, t8m commented on roadmap.md
> +* Optimization of of algorithm fetching to improve performance
Duplicate `of`

2024-04-22 13:55 UTC, t8m commented on roadmap.md
> +* DTLS 1.3 support
This is unlikely to make 3.4.

2024-04-24 14:19 UTC, hlandau requested changes

2024-04-24 14:19 UTC, hlandau commented on roadmap.md
> +* QUIC Unreliable datagram extensions (RFC 9221)
```suggestion
* Server-side QUIC support
```

We are not shipping RFC 9221 for 3.4...

2024-04-25 09:05 UTC, t8m approved these changes

2024-04-29 08:04 UTC, hlandau approved these changes

2024-04-29 13:17 UTC, t8m commented
Merged. Thank you.

2024-04-29 13:17 UTC, closed without merging