Re-org to replace "team" with "omc"
openssl/web pull request #7
Opened 2017-05-31 13:43 UTC by richsalz

2017-05-31 13:54 UTC, mattcaswell requested changes

2017-05-31 13:54 UTC, mattcaswell commented on docs/faq.txt
>  You can check authenticity using pgp or gpg. You need the OpenSSL team
Reference to team here

2017-05-31 13:54 UTC, mattcaswell commented on community/omc.html
> +	  The current OMC consists of (in alphabetical order):
Don't we need a separate list of committers too? At the moment the list will be largely the same, but very soon it will be different.

2017-05-31 13:54 UTC, mattcaswell commented on policies/index.html
> +            <a href="bylaws.html">project bylaws</a>.
project project bylaws?

2017-05-31 14:03 UTC, richsalz commented on community/omc.html
> +	  The current OMC consists of (in alphabetical order):
yes we will.  I'll work on adding that as a separate change.

2017-05-31 14:04 UTC, richsalz commented
I fixed the other two issues; updated commit pushed.

2017-05-31 14:07 UTC, mattcaswell commented on community/omc.html
> +	  The current OMC consists of (in alphabetical order):
Ok. Eventually we'll need an alumni section too I guess. When you do your other PR you might want to think about adding github names to the table too.

2017-05-31 14:08 UTC, mattcaswell approved these changes

2017-05-31 14:11 UTC, levitte commented on community/omc.html
> +	  The current OMC consists of (in alphabetical order):
I'm thinking this should be automated.  I do have some thoughts on that, based on internal databases...

2017-05-31 14:11 UTC, levitte commented on community/omc.html
> +	  The current OMC consists of (in alphabetical order):
... but that doesn't have to happen nownownow...

2017-05-31 14:12 UTC, levitte approved these changes

2017-05-31 14:15 UTC, mattcaswell commented on community/omc.html
> +	  The current OMC consists of (in alphabetical order):
> ... but that doesn't have to happen nownownow...

I'd suggest doing it manually until we're happy with how it looks, and then automate it.

2017-05-31 14:17 UTC, levitte commented on community/omc.html
> +	  The current OMC consists of (in alphabetical order):
Good thinking

2017-06-13 12:46 UTC, richsalz commented
forgot to close.

2017-06-13 12:46 UTC, closed without merging